x-core-env: &core-env
  ConnectionStrings__PostgresCore: ${POSTGRES_CONNECTION}
  ConnectionStrings__MongoTimeline: ${MONGO_CONNECTION}
  MONGO_TIMELINE_DATABASE: ${MONGO_TIMELINE_DATABASE}

services:

  core-data:
    image: postgres:16
    container_name: core-data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CORE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - core_data:/var/lib/postgresql/data

  timeline-data:
    image: mongo:7
    container_name: timeline-data
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - timeline_data:/data/db

  api:
    build: ./api
    container_name: tasksystem-api
    restart: unless-stopped
    environment:
      <<: *core-env
      CORE_DATA_USER: ${CORE_DATA_USER}
      CORE_DATA_PASSWORD: ${CORE_DATA_PASSWORD}
    depends_on:
      - core-data
      - timeline-data
    ports:
      - "5001:8080"

  client:
    build: ./client
    container_name: tasksystem-client
    restart: unless-stopped
    ports:
      - "3001:5173"
    depends_on:
      - api

  migrator:
    build: ./migrator
    container_name: tasksystem-migrator
    environment:
      ConnectionStrings__PostgresCore: ${POSTGRES_CONNECTION}
      CORE_DATA_USER: ${CORE_DATA_USER}
      CORE_DATA_PASSWORD: ${CORE_DATA_PASSWORD}
    depends_on:
      - core-data
    profiles:
      - migrate

  tests:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: tasksystem-tests
    command: >
      dotnet test
      --no-build
      --verbosity normal
    environment:
      <<: *core-env
    depends_on:
      - core-data
      - timeline-data
    profiles:
      - test

volumes:
  core_data:
  timeline_data: